name: "BuildAndTest"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test driver
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [ 'python2.7', 'python3.6' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Environment 01
      run: ${{ matrix.runtime }} -m pip install --upgrade setuptools
    - name: Install requirements
      run: ${{ matrix.runtime }} -m pip install -U -r requirements.txt -r test-requirements.txt
    - name: Install Codacy coverage
      run:  ${{ matrix.runtime }} -m pip install codacy-coverage
    - name: Run Tests
      run: py.test -v --cov=swimlane --cov-report=xml
    - name: Post result
      run: python-codacy-coverage -r coverage.xml

